services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  python_app:
    build: .
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
    command: python /app/src/main.py
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true
    tty: true

networks:
  app_network:

volumes:
  redis_data:
